data_layers:
  region_fc: sacog_region
  fc_speed_data: npmrds_metrics_v8 #npmrds speed data
  accdata_fc: Sugar_access_data_latest # sugar accessibility polygon data
  collisions_fc: collisions_tims_2015_2019_fwytag # collision point data
  trn_svc_fc: transit_stopcount_2019 # transit stop event data; point file
  freight_route_fc: STAATruckRoutes # STAA truck route lines
  intersections_base_fc: intersections_2021
  comm_types_fc: comm_type_jurspec_dissolve

  reg_centerline_fc: RegionalCenterline_Oct2021
  reg_artcollcline_fc: OSM_ArterialCollector_2022 # ArterialCollector_2019 # road centerlines but for collectors and above (no local streets/alleys)

  reg_bikeway_fc: BikeRte_C1_C2_C4_2022 # BikeRte_C1_C2_C4_2017

  proj_line_template_fc: Project_Line_Template # has symbology that the project line will use.